### ISSUE TITLE
Create release of v3 for PHP 8.2

### ISSUE THREAD

**Issue by freekmurze** [openspout/openspout#110]
Could you create a new release of v3 that allow the use of PHP 8.2
It's highly likely that v3 will just work on PHP 8.2

That would fix the tests of my dependant package: https://github.com/spatie/simple-excel

**Comment by Slamdunk** [comment]
I'm sorry `v3` has been EOLed.

Upgrade to `v4` should be easy tough: https://github.com/openspout/openspout/blob/4.x/UPGRADE.md

**Comment by cmanley** [comment]
It would be nice to have a little PHP version support overlap next time.
Why: because currently as it stands one currently can't gracefully upgrade from Debian 11 (PHP 7.4) to 12 (PHP 8) without simultaneously having to upgrade and release all code that uses OpenSpout.
If one uses Docker then this process is less of an issue obviously.
