### ISSUE TITLE
feat: allow reading from and writing to php resource

### ISSUE THREAD

**Issue by darthf1** [openspout/openspout#71]
Hi!

Thanks for creating this fork. Migration was easy and with the types and additional features its a huge improvement over the original codebase.

I have a feature request; Is it possible to allow reading from and writing to a php resource? At least for CSV, I'm not sure if it's possible for XLSX (and other formats) as well.

I noticed the current CSV Reader already [converts the filePath to a resource](https://github.com/openspout/openspout/blob/4.x/src/Reader/CSV/Reader.php#L74). Maybe it's as easy as changing
```php
protected function openReader(string $filePath): void
```
to
```php
protected function openReader(string | resource $filePath): void
```
and check which parameter type has passed?

As for the CSV Writer, I'm not sure if it is [the same case](https://github.com/openspout/openspout/blob/4.x/src/Writer/AbstractWriter.php#L42)?
```php
final public function openToFile($outputFilePath): void
```
to
```php
final public function openToFile(string | resource $outputFilePath): void
```

**Comment by Slamdunk** [comment]
Hi, may I ask what's your use case?

**Comment by darthf1** [comment]
Yes ofcourse,

My filesystem is abstracted using [Flysystem](https://flysystem.thephpleague.com/docs/usage/filesystem-api/) and I'm making heavy usage of `FilesystemReader::readStream` and `FilesystemWriter::writeStream` methods.

If the reader supports streams, I can pass the result of `FilesystemReader::readStream` directly without additional writes to disk, and vice versa for the writer.

Also, not the least, with `Flysystem` I can only get the contents of the file and not the path to the file since files do not need to "live" on the current filesystem.

**Comment by Slamdunk** [comment]
Regarding the Writer, although it should be possible to write to a user-provided stream, it wouldn't work as you expect with Flysystem: `FilesystemWriter::writeStream` expects an already filled stream, you cannot pass to it a stream that still needs to receive the data. So at least a `php://memory` intermediate stream would be needed anyway and in my experience that's more of a burden rather than an help.

Regarding the Reader, only the CSV one could achieve your goal as both ODS and XLSX rely on `ZipStream::open` which doesn't accept a stream.
And I don't like very much to add a feature so specific to a single component.

I have [a decent experience](https://github.com/Slamdunk/flysystem-compress-and-encrypt-proxy) with `Flysystem`, streams and filesystem operations on PHP, and although bypassing the disk entirely seems good in theory I strongly suggest you to rely on physical temporary files for intermediate steps, you'll save yourself a lot of pita.

**Comment by darthf1** [comment]
>  And I don't like very much to add a feature so specific to a single component.

I fully agree. It should only be done if possible for all formats.

Thank you for your reply and your advice. I'll close this request for now.

**Comment by homersimpsons** [comment]
Sorry for reviving this old issue, but do you think this could be re-considered? As I see we already have an `openToBrowser` function and we now are handling a `filePointer` resource, hence I believe we could have a `openToResource` where we could pass a `fopen("php://memory", "rw");` to not require access to the file system.
